server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dataflow_db}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: ${JWT_SECRET:DataFlowPlatformSuperSecretKeyForJWTAuthTokenGeneration2026!}
    expiration-ms: 3600000 # 1 hour
    refresh-expiration-ms: 86400000 # 24 hours
